--------------------------------------------------------------------------------
-- Laravel system tables (Oracle 11g+ compatible)
-- Untuk siklik-php82 yang DB_CONNECTION=oracle_siklik.
--
-- Tabel ini dibutuhkan oleh:
--   SESSION_DRIVER=database  -> tabel SESSIONS
--   CACHE_STORE=database     -> tabel CACHE, CACHE_LOCKS
--   QUEUE_CONNECTION=database-> tabel JOBS, JOB_BATCHES
--
-- Cara jalanin (dari sqlplus / SQL Developer):
--   sqlplus siklik/siklik@//127.0.0.1:1521/orcl @database/sql/laravel_system_tables_oracle.sql
--
-- Catatan:
-- * `KEY` adalah reserved word Oracle, jadi kolomnya dipakai pakai quoted
--   identifier "KEY" (uppercase). Driver yajra/oci8 generate query pakai
--   "KEY" uppercase quoted, jadi DDL juga harus uppercase. Kalau bikin
--   "key" lowercase, Oracle treat sebagai kolom berbeda → ORA-00904.
-- * Auto-increment di JOBS pakai sequence + trigger (Oracle 11g style).
--   Kalau pakai Oracle 12c+, bisa diganti GENERATED BY DEFAULT AS IDENTITY.
-- * Kolom timestamp Laravel (last_activity, expiration, created_at, dll) di
--   SESSION/CACHE/JOBS itu UNIX EPOCH int — bukan DATE — jadi pakai NUMBER(10).
--------------------------------------------------------------------------------

-- ============================================================
-- SESSIONS  (untuk SESSION_DRIVER=database)
-- ============================================================
CREATE TABLE sessions (
    id              VARCHAR2(255)  NOT NULL,
    user_id         NUMBER(19),
    ip_address      VARCHAR2(45),
    user_agent      CLOB,
    payload         CLOB           NOT NULL,
    last_activity   NUMBER(10)     NOT NULL,
    CONSTRAINT pk_sessions PRIMARY KEY (id)
);

CREATE INDEX idx_sessions_user_id       ON sessions (user_id);
CREATE INDEX idx_sessions_last_activity ON sessions (last_activity);


-- ============================================================
-- CACHE  (untuk CACHE_STORE=database)
-- ============================================================
CREATE TABLE cache (
    "KEY"        VARCHAR2(255)  NOT NULL,
    value        CLOB           NOT NULL,
    expiration   NUMBER(10)     NOT NULL,
    CONSTRAINT pk_cache PRIMARY KEY ("KEY")
);


CREATE TABLE cache_locks (
    "KEY"        VARCHAR2(255)  NOT NULL,
    owner        VARCHAR2(255)  NOT NULL,
    expiration   NUMBER(10)     NOT NULL,
    CONSTRAINT pk_cache_locks PRIMARY KEY ("KEY")
);


-- ============================================================
-- JOBS  (untuk QUEUE_CONNECTION=database)
-- ============================================================
CREATE TABLE jobs (
    id            NUMBER(19)     NOT NULL,
    queue         VARCHAR2(255)  NOT NULL,
    payload       CLOB           NOT NULL,
    attempts      NUMBER(3)      NOT NULL,
    reserved_at   NUMBER(10),
    available_at  NUMBER(10)     NOT NULL,
    created_at    NUMBER(10)     NOT NULL,
    CONSTRAINT pk_jobs PRIMARY KEY (id)
);

CREATE INDEX idx_jobs_queue ON jobs (queue);

-- Sequence + trigger untuk auto-increment id (Oracle 11g)
CREATE SEQUENCE jobs_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER jobs_bi
    BEFORE INSERT ON jobs
    FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT jobs_seq.NEXTVAL INTO :NEW.id FROM dual;
    END IF;
END;
/


-- ============================================================
-- JOB_BATCHES
-- ============================================================
CREATE TABLE job_batches (
    id              VARCHAR2(255)  NOT NULL,
    name            VARCHAR2(255)  NOT NULL,
    total_jobs      NUMBER(10)     NOT NULL,
    pending_jobs    NUMBER(10)     NOT NULL,
    failed_jobs     NUMBER(10)     NOT NULL,
    failed_job_ids  CLOB           NOT NULL,
    options         CLOB,
    cancelled_at    NUMBER(10),
    created_at      NUMBER(10)     NOT NULL,
    finished_at     NUMBER(10),
    CONSTRAINT pk_job_batches PRIMARY KEY (id)
);


-- ============================================================
-- VERIFY (jalankan ini setelah create untuk konfirmasi)
-- ============================================================
-- SELECT table_name FROM user_tables
-- WHERE table_name IN ('SESSIONS','CACHE','CACHE_LOCKS','JOBS','JOB_BATCHES')
-- ORDER BY table_name;

COMMIT;
